events {
    worker_connections  1024;
}

http{
        server{
                listen 80;
                location / {
                        proxy_pass "http://<MAIN_API_HOST>:8000";
                }
                location /api/ {
                        proxy_pass "http://<COMMENTS_API_HOST>/api/";
                }
        }
}
