// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthor = "authors"

// Author mapped from table <authors>
type Author struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DisplayName string `gorm:"column:display_name;not null" json:"display_name"`
}

// TableName Author's table name
func (*Author) TableName() string {
	return TableNameAuthor
}
