// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBookToAuthor = "book_to_authors"

// BookToAuthor mapped from table <book_to_authors>
type BookToAuthor struct {
	BookID   int64 `gorm:"column:book_id;primaryKey" json:"book_id"`
	AuthorID int64 `gorm:"column:author_id;primaryKey" json:"author_id"`
}

// TableName BookToAuthor's table name
func (*BookToAuthor) TableName() string {
	return TableNameBookToAuthor
}
