// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/jackc/pgx/v5/pgtype"

const TableNameBook = "books"

// Book mapped from table <books>
type Book struct {
	ID          int64       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title       string      `gorm:"column:title;not null" json:"title"`
	Description string      `gorm:"column:description;not null" json:"description"`
	PublihsedOn pgtype.Date `gorm:"column:publihsed_on;not null" json:"publihsed_on"`
	Amount      int16       `gorm:"column:amount;not null" json:"amount"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
