// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

const TableNameBookReturnTransaction = "book_return_transactions"

// BookReturnTransaction mapped from table <book_return_transactions>
type BookReturnTransaction struct {
	RequestID uuid.UUID `gorm:"column:request_id;primaryKey" json:"request_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName BookReturnTransaction's table name
func (*BookReturnTransaction) TableName() string {
	return TableNameBookReturnTransaction
}
