// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/jackc/pgx/v5/pgtype"

const TableNameBook = "books"

// Book mapped from table <books>
type Book struct {
	ID          int64       `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Title       string      `gorm:"column:title;type:text;not null" json:"title"`
	Description string      `gorm:"column:description;type:text;not null" json:"description"`
	PublishedOn pgtype.Date `gorm:"column:published_on;type:date;not null" json:"published_on"`
	Amount      int16       `gorm:"column:amount;type:smallint;not null" json:"amount"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
