// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBookToGenre = "book_to_genres"

// BookToGenre mapped from table <book_to_genres>
type BookToGenre struct {
	BookID  int64 `gorm:"column:book_id;primaryKey;constraint:OnUpdate:CASCADE,OnDelete:CASCADE" json:"book_id"`
	GenreID int16 `gorm:"column:genre_id;primaryKey;constraint:OnUpdate:CASCADE,OnDelete:CASCADE" json:"genre_id"`
}

// TableName BookToGenre's table name
func (*BookToGenre) TableName() string {
	return TableNameBookToGenre
}
