// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/google/uuid"

const TableNameBookLendRequest = "book_lend_requests"

// BookLendRequest mapped from table <book_lend_requests>
type BookLendRequest struct {
	ID     uuid.UUID `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	UserID int64     `gorm:"column:user_id;type:bigint;not null;constraint:OnUpdate:CASCADE,OnDelete:RESTRICT" json:"user_id"`
	BookID int64     `gorm:"column:book_id;type:bigint;not null;constraint:OnUpdate:CASCADE,OnDelete:RESTRICT" json:"book_id"`
}

// TableName BookLendRequest's table name
func (*BookLendRequest) TableName() string {
	return TableNameBookLendRequest
}
