[package]
name = "comments-service"
version.workspace = true
edition.workspace = true

[profile.release]
lto = true
opt-level = 3

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.dev.package.backtrace]
opt-level = 3

[profile.dev.package.askama]
opt-level = 3

[dependencies]
askama.workspace = true
askama_axum.workspace = true
axum = { workspace = true, features = ["macros"] }
axum-extra = { workspace = true, features = ["cookie"] }
base64 = "0.22"
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
itertools.workspace = true
serde.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls", "macros", "postgres", "uuid"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid = { version = "1.11", features = ["serde", "v7"] }

[dev-dependencies]
pretty_assertions.workspace = true
